name: heat

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: check out repo
        uses: actions/checkout@v2

      - name: dump env
        run: env

      - name: install pylint
        run: pip install pylint python-dateutil numpy matplotlib

      - name: run pylint total_energy_get_data
        run: pylint total_energy_get_data.py
        working-directory: eia

      - name: run pylint total_energy_make_chart
        run: pylint total_energy_make_chart.py
        working-directory: eia

      - name: run pylint eia_get_routes
        run: pylint eia_get_routes.py
        working-directory: eia
